type User @table {
  id: String! @primaryKey
  username: String!
  email: String!
  createdAt: Timestamp! @default(expr: "request.time")
  totalPoints: Int @default(value: 0)
  rank: Int
}

type Match @table {
  id: String! @primaryKey
  team1Id: String!
  team2Id: String!
  date: Timestamp!
  venue: String!
  status: String! @default(value: "upcoming")
}

type Prediction @table {
  id: String! @primaryKey # matchId_userId
  user: User!
  matchId: String!
  team1Score: Int!
  team2Score: Int!
  winner: String!
  firstInningRange: String
  secondInningRange: String
  teamMore4s: String
  teamMore6s: String
  playerMax6s: String
  fantasyPlayer: String
  playerOfMatch: String
  superStriker: String
  mostDotBalls: String
  submittedAt: Timestamp! @default(expr: "request.time")
  points: Int
  scored: Boolean @default(value: false)
}